name       : epiphany
version    : 3.18.7
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/epiphany/3.18/epiphany-3.18.7.tar.xz : 90513aea04d66a4387da076db1b8104b54d3657a81aff2d629b527b32d9eec76
license    : GPL-2.0
summary    : Epiphany is a GNOME web browser based on the WebKit rendering engine.
description: |
    Epiphany is a GNOME web browser based on the WebKit rendering engine.
component  : network.web.browser
rundeps    :
    - glib-networking
builddeps  :
    - glib-networking
    - gnome-common
    - itstool
    - pkgconfig(appstream-glib)
    - pkgconfig(avahi-gobject)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(x11)
    - yelp-tools
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-linking-of-web_extension-with-gnome-desktop-3.0.patch
    autoreconf -vfi
    %configure
build      : |
    %make
install    : |
    %make_install
