name       : epiphany
version    : 3.32.1.2
release    : 43
source     :
    - https://download.gnome.org/sources/epiphany/3.32/epiphany-3.32.1.2.tar.xz : a8284fb9bbc8b7914a154a8eac1598c8b59ae421e0d685146fb48198427926be
license    : GPL-2.0-only
summary    : Epiphany is a GNOME web browser based on the WebKit rendering engine.
description: |
    Epiphany is a GNOME web browser based on the WebKit rendering engine.
component  : network.web.browser
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(avahi-gobject)
    - pkgconfig(gcr-3)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hogweed)
    - pkgconfig(icu-io)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - glib-networking
    - gnome-common
    - itstool
    - yelp-tools
rundeps    :
    - glib-networking
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Solus-blog-as-default-homepage.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
