name       : gnome-web
version    : '44.5'
release    : 57
source     :
    - https://download.gnome.org/sources/epiphany/44/epiphany-44.5.tar.xz : 3c475e04ed2a0f410cb44b96937563697079193ac9b7a50c91485fb9b08315ab
license    : GPL-3.0-or-later
summary    : GNOME web browser based on the WebKit rendering engine.
description: |
    GNOME web browser based on the WebKit rendering engine.
component  : network.web.browser
replaces   :
    - epiphany
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gcr-4)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(hogweed)
    - pkgconfig(icu-io)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libportal-gtk4)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(libxslt)
    - pkgconfig(sqlite3)
    - pkgconfig(webkitgtk-6.0)
    - desktop-file-utils
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Solus-blog-as-default-homepage.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
