name       : epiphany
version    : 3.16.2
release    : 2
source     :
    - https://download.gnome.org/sources/epiphany/3.16/epiphany-3.16.2.tar.xz : a621b5f443bc168980d12452f1a031e0a50d99ffc825989a38b14d398def73e6
license    : GPL-2.0
clang      : no
summary    : Epiphany is a GNOME web browser based on the WebKit rendering engine.
description: |
    Epiphany is a GNOME web browser based on the WebKit rendering engine.
builddeps  :
    - pkgconfig(nss)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libsecret-1)
    - pkgconfig(libnotify)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gcr-3)
    - pkgconfig(avahi-gobject)
    - itstool
    - glib-networking
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
