name       : epiphany
version    : 3.26.2
release    : 28
source     :
    - https://download.gnome.org/sources/epiphany/3.26/epiphany-3.26.2.tar.xz : 46757b74d1e7d7f78a7c6377dba2db4e2ed470efe4cc7067d4f0facf1d3ec3a9
license    : GPL-2.0
summary    : Epiphany is a GNOME web browser based on the WebKit rendering engine.
description: |
    Epiphany is a GNOME web browser based on the WebKit rendering engine.
component  : network.web.browser
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(avahi-gobject)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hogweed)
    - pkgconfig(icu-io)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - glib-networking
    - gnome-common
    - itstool
    - yelp-tools
rundeps    :
    - glib-networking
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Solus-blog-as-default-homepage.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
