name       : epiphany
version    : 3.18.0
release    : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/epiphany/3.18/epiphany-3.18.0.tar.xz : d5ba67a8cd85c80b81e076862bcab3fc376ba51b0a1536ca7430608d1f50491d
license    : GPL-2.0
clang      : no
summary    : Epiphany is a GNOME web browser based on the WebKit rendering engine.
description: |
    Epiphany is a GNOME web browser based on the WebKit rendering engine.
rundeps    :
    - glib-networking
builddeps  :
    - pkgconfig(nss)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(x11)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libsecret-1)
    - pkgconfig(libnotify)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gcr-3)
    - pkgconfig(avahi-gobject)
    - itstool
    - glib-networking
    - gnome-common
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-linking-of-web_extension-with-gnome-desktop-3.0.patch
    autoreconf -vfi
    %configure
build      : |
    %make
install    : |
    %make_install
