name       : gnome-web
version    : 43.1
release    : 55
source     :
    - https://download.gnome.org/sources/epiphany/43/epiphany-43.1.tar.xz : e86ead27cb9982815150664de3bf20faf375f77b8065b02b31180c65b6bbebb4
license    : GPL-3.0-or-later
summary    : GNOME web browser based on the WebKit rendering engine.
description: |
    GNOME web browser based on the WebKit rendering engine.
component  : network.web.browser
replaces   :
    - epiphany
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(gcr-3)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(hogweed)
    - pkgconfig(icu-io)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libnotify)
    - pkgconfig(libportal-gtk3)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.1)
    - desktop-file-utils
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Solus-blog-as-default-homepage.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
