name       : epiphany
version    : 3.24.3
release    : 23
source     :
    - https://download.gnome.org/sources/epiphany/3.24/epiphany-3.24.3.tar.xz : fef51676310d9f37e18c9b2d778254232eb17cccd988c2d1ecf42c7b2963a154
license    : GPL-2.0
summary    : Epiphany is a GNOME web browser based on the WebKit rendering engine.
description: |
    Epiphany is a GNOME web browser based on the WebKit rendering engine.
component  : network.web.browser
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(avahi-gobject)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - glib-networking
    - gnome-common
    - itstool
    - yelp-tools
rundeps    :
    - glib-networking
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
