name       : epiphany
version    : 3.34.0
release    : 47
source     :
    - https://download.gnome.org/sources/epiphany/3.34/epiphany-3.34.0.tar.xz : 6ba1e66f8a987a0bd6618fbf8ffb26ee045994c24f508a69106f7110d1b79d13
license    : GPL-2.0-only
summary    : Epiphany is a GNOME web browser based on the WebKit rendering engine.
description: |
    Epiphany is a GNOME web browser based on the WebKit rendering engine.
component  : network.web.browser
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(avahi-gobject)
    - pkgconfig(gcr-3)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hogweed)
    - pkgconfig(icu-io)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libdazzle-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - glib-networking
    - gnome-common
    - itstool
    - yelp-tools
rundeps    :
    - glib-networking
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Solus-blog-as-default-homepage.patch
    %meson_configure -Dunit_tests=disabled
build      : |
    %meson_build
install    : |
    %meson_install
