name       : epiphany
version    : 3.28.2.1
release    : 38
source     :
    - https://download.gnome.org/sources/epiphany/3.28/epiphany-3.28.2.1.tar.xz : baa4e9f0ac0b1e95fa2027af796859114f448f0f274976c30c9b8db734c6402d
license    : GPL-2.0-only
summary    : Epiphany is a GNOME web browser based on the WebKit rendering engine.
description: |
    Epiphany is a GNOME web browser based on the WebKit rendering engine.
component  : network.web.browser
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(avahi-gobject)
    - pkgconfig(gcr-3)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hogweed)
    - pkgconfig(icu-io)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - glib-networking
    - gnome-common
    - itstool
    - yelp-tools
rundeps    :
    - glib-networking
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-Solus-blog-as-default-homepage.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
