name       : epiphany
version    : 3.22.6
release    : 17
source     :
    - http://ftp.gnome.org/pub/gnome/sources/epiphany/3.22/epiphany-3.22.6.tar.xz : de7ea87dc450702bde620033f9e2ce807859727d007396d86b09f2b82397fcc2
license    : GPL-2.0
summary    : Epiphany is a GNOME web browser based on the WebKit rendering engine.
description: |
    Epiphany is a GNOME web browser based on the WebKit rendering engine.
component  : network.web.browser
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(avahi-gobject)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(x11)
    - glib-networking
    - gnome-common
    - itstool
    - yelp-tools
rundeps    :
    - glib-networking
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
