name       : epiphany
version    : 3.20.3
release    : 15
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/epiphany/3.20/epiphany-3.20.3.tar.xz : 4d9de1bdb44c14adf25aa6dc02ea3de60925cff5eb01fe89545e6032c9b424a2
license    : GPL-2.0
summary    : Epiphany is a GNOME web browser based on the WebKit rendering engine.
description: |
    Epiphany is a GNOME web browser based on the WebKit rendering engine.
component  : network.web.browser
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(avahi-gobject)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(x11)
    - glib-networking
    - gnome-common
    - itstool
    - yelp-tools
rundeps    :
    - glib-networking
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
